config/routes.rb
Mapadacultura::Application.routes.draw do
  devise_for :users
    as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  resources :entidade_equipamentos, :path => :registros do
    resources :questionario_basico_entidades, :path => 'questionario'
    resources :fotos,  :controller => "fotos"
    resources :videos, :controller => "videos" do
      get 'view', :action => 'view', :as => 'view'
    end

    collection do
      get 'entidades/',           :action => 'entidades'
      get 'equipamentos/',        :action => 'equipamentos'
      get 'view/entidade/:id',    :action => 'entidade'
      get 'view/equipamento/:id', :action => 'equipamento'
      get 'view/atividade/:id',   :action => 'atividade', :as => 'atividade'
      get 'view/subcategoria/:id',:action => 'subcategoria', :as => 'subcategoria'
      get 'apresenta/:id',        :action => 'apresenta', :as => 'apresenta'
      get 'publish/:id',          :action => 'publish',   :as => 'publish'
      get 'evaluate'
      get 'search'
    end
  end

  resources :tipos
  resources :tipo_equipamentos
  resources :tipo_naturezas
  resources :atividades, :path => :categorias
  resources :subcategorias
  resources :users

  get '/estados/:sigla/cidades', :as => :cidades, :to => 'cidades#index'
  get '/cep/:cep', :to => 'application#cep'

  get "home/index"
  get "home/sobre"

  root :to => 'home#index'
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me, :cpf, :firstname, :lastname, :admin


  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  validates :cpf, :presence => true,
            :uniqueness => true

  validates :firstname, :presence => true,
                        :length => { :minimum => 3, :maximum => 254 }

  validates :lastname, :presence => true,
                       :length => { :minimum => 3, :maximum => 254 }

  usar_como_cpf :cpf

  has_many :entidade_equipamentos
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :admin_user

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, :notice => 'O Usuário foi Atualizado com Sucesso' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, :notice => 'O Usuário foi Apagado com Sucesso' }

      format.json { head :no_content }
    end
  end
end

app/views/users/shared/_links.erb
<div class="users-shared-links">
<%- if controller_name != 'sessions' %>
  <%= link_to "Logar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Esqueceu a Senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu as instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu as instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</div>