config/routes.rb
Mapadacultura::Application.routes.draw do
  devise_for :users
    as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  resources :entidade_equipamentos, :path => :registros do
    resources :questionario_basico_entidades, :path => 'questionario'
    resources :fotos,  :controller => "fotos"
    resources :videos, :controller => "videos" do
      get 'view', :action => 'view', :as => 'view'
    end

    collection do
      get 'entidades/',           :action => 'entidades'
      get 'equipamentos/',        :action => 'equipamentos'
      get 'view/entidade/:id',    :action => 'entidade'
      get 'view/equipamento/:id', :action => 'equipamento'
      get 'view/atividade/:id',   :action => 'atividade', :as => 'atividade'
      get 'view/subcategoria/:id',:action => 'subcategoria', :as => 'subcategoria'
      get 'apresenta/:id',        :action => 'apresenta', :as => 'apresenta'
      get 'publish/:id',          :action => 'publish',   :as => 'publish'
      get 'evaluate'
      get 'search'
    end
  end

  resources :tipos
  resources :tipo_equipamentos
  resources :tipo_naturezas
  resources :atividades, :path => :categorias
  resources :subcategorias
  resources :users

  get '/estados/:sigla/cidades', :as => :cidades, :to => 'cidades#index'
  get '/cep/:cep', :to => 'application#cep'

  get "home/index"
  get "home/sobre"

  root :to => 'home#index'
end

app/models/questionario_basico_entidade.rb
# encoding: utf-8

class QuestionarioBasicoEntidade < ActiveRecord::Base
  attr_accessible :acoes_desenvolvidas, :frequencia_acoes, :frequencia_participacao_eventos, :frequencia_producao_eventos, :participa_eventos, :principais_atividades, :produz_eventos, :inicio_atividades, :user_id, :entidade_equipamento_id

  belongs_to :entidade_equipamento
  belongs_to :user

  serialize :acoes_desenvolvidas, Hash
  serialize :frequencia_acoes, Hash
  serialize :frequencia_participacao_eventos, Hash
  serialize :frequencia_producao_eventos, Hash
end

app/controllers/questionario_basico_entidades_controller.rb
# encoding: utf-8

class QuestionarioBasicoEntidadesController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /questionario_basico_entidades
  # GET /questionario_basico_entidades.json
  def index
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])
    @questionario_basico_entidades = QuestionarioBasicoEntidade.where("entidade_equipamento_id = #{@entidade_equipamento.id}").limit(1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questionario_basico_entidades }
    end
  end

  # GET /questionario_basico_entidades/1
  # GET /questionario_basico_entidades/1.json
  def show
    @questionario_basico_entidade = QuestionarioBasicoEntidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questionario_basico_entidade }
    end
  end

  # GET /questionario_basico_entidades/new
  # GET /questionario_basico_entidades/new.json
  def new
    @questionario_basico_entidade = QuestionarioBasicoEntidade.new
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    return false if !owner_verify(@entidade_equipamento, entidade_equipamentos_url)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questionario_basico_entidade }
    end
  end

  # GET /questionario_basico_entidades/1/edit
  def edit
    @questionario_basico_entidade = QuestionarioBasicoEntidade.find(params[:id])
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    return false if !owner_verify(@entidade_equipamento, entidade_equipamentos_url)
  end

  # POST /questionario_basico_entidades
  # POST /questionario_basico_entidades.json
  def create
    @questionario_basico_entidade = QuestionarioBasicoEntidade.new(params[:questionario_basico_entidade])
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])
    
    respond_to do |format|
      if @questionario_basico_entidade.save
        format.html { redirect_to entidade_equipamento_questionario_basico_entidades_path(@entidade_equipamento), notice: 'O Questionario foi Respondido com Sucesso.' }
        format.json { render json: @questionario_basico_entidade, status: :created, location: @questionario_basico_entidade }
      else
        format.html { render action: "new" }
        format.json { render json: @entidade_equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questionario_basico_entidades/1
  # PUT /questionario_basico_entidades/1.json
  def update
    @questionario_basico_entidade = QuestionarioBasicoEntidade.find(params[:id])
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    respond_to do |format|
      if @questionario_basico_entidade.update_attributes(params[:questionario_basico_entidade])
        format.html { redirect_to entidade_equipamento_questionario_basico_entidades_path(@entidade_equipamento), notice: 'O Questionario foi Atualizado com Sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entidade_equipamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionario_basico_entidades/1
  # DELETE /questionario_basico_entidades/1.json
  def destroy
    @questionario_basico_entidade = QuestionarioBasicoEntidade.find(params[:id])
    @entidade_equipamento = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    return false if !owner_verify(entidade, entidade_equipamentos_url)

    @questionario_basico_entidade.destroy

    respond_to do |format|
      format.html { redirect_to entidade_equipamento_questionario_basico_entidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questionario_basico_entidades_helper.rb
module QuestionarioBasicoEntidadesHelper
end

app/views/questionario_basico_entidades/_form.html.erb
<%= form_for [@entidade_equipamento, @questionario_basico_entidade], :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
  <%= f.label :inicio_atividades, 'Início das Atividades', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :inicio_atividades, :class => 'jquery-ui-date' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :principais_atividades, 'Resumo das Atividades', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :principais_atividades, :class => 'span6', :rows => 8 %>
  </div>
</div>

<div class="control-group">
  <%= f.label :acoes_desenvolvidas, 'Ações Desenvolvidas', :class => 'control-label' %>
  <div class="controls">
    <%= f.fields_for :acoes_desenvolvidas, @questionario_basico_entidade.acoes_desenvolvidas do |n| %>
    <table>
      <tr>
        <td><%= n.check_box 'Cinema', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Cinema'] == "1" } %> Cinema </td>
        <td><%= n.check_box 'Teatro', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Teatro'] == "1" } %> Teatro </td>
        <td><%= n.check_box 'Dança',  { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Dança'] == "1" } %> Dança </td>
        <td><%= n.check_box 'Música', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Música'] == "1" } %> Música </td>
      </tr>
      <tr>
        <td><%= n.check_box 'Artes Plásticas', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Artes Plásticas'] == "1" } %> Artes Plásticas </td>
        <td><%= n.check_box 'Artesanato',  { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Artesanato'] == "1" } %> Artesanato </td>
        <td><%= n.check_box 'Circo',       { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Circo'] == "1" } %> Circo </td>
        <td><%= n.check_box 'Fotografia',  { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Fotografia'] == "1" } %> Fotografia </td>
      </tr>
      <tr>
        <td><%= n.check_box 'Audiovisual', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Audiovisual'] == "1" } %> Audiovisual </td>
        <td><%= n.check_box 'Capoeira',    { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Capoeira'] == "1" } %> Capoeira </td>
        <td><%= n.check_box 'Inclusão Digital', { :checked => @questionario_basico_entidade.acoes_desenvolvidas['Inclusão Digital'] == "1" } %> Inclusão Digital </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

<div class="control-group">
  <%= f.label :frequencia_acoes, 'Frequência das Ações', :class => 'control-label' %>
  <div class="controls">
    <%= f.fields_for :frequencia_acoes, @questionario_basico_entidade.frequencia_acoes do |n| %>
    <table>
      <tr>
        <td><%= n.check_box 'Diário', { :checked => @questionario_basico_entidade.frequencia_acoes['Diário'] == "1" } %> Diário </td>
        <td><%= n.check_box 'Semanal', { :checked => @questionario_basico_entidade.frequencia_acoes['Semanal'] == "1" } %> Semanal </td>
        <td><%= n.check_box 'Mensal', { :checked => @questionario_basico_entidade.frequencia_acoes['Mensal'] == "1" } %> Mensal </td>
        <td><%= n.check_box 'Anual', { :checked => @questionario_basico_entidade.frequencia_acoes['Anual'] == "1" } %> Anual </td>
        <td><%= n.check_box 'Outros', { :checked => @questionario_basico_entidade.frequencia_acoes['Outros'] == "1" } %> Outros </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

<div class="control-group">
  <%= f.label :produz_eventos, 'Produz Eventos?', :class => 'control-label' %>
  <div class="controls">
    <%= f.select :produz_eventos, 'Sim' => true, 'Não' => false %>
  </div>
</div>

<div class="control-group">
  <%= f.label :frequencia_producao_eventos, 'Produz com que Frequência', :class => 'control-label' %>
  <div class="controls">
    <%= f.fields_for :frequencia_producao_eventos, @questionario_basico_entidade.frequencia_producao_eventos do |n| %>
    <table>
      <tr>
        <td><%= n.check_box 'Diário', { :checked => @questionario_basico_entidade.frequencia_producao_eventos['Diário'] == "1" } %> Diário </td>
        <td><%= n.check_box 'Semanal', { :checked => @questionario_basico_entidade.frequencia_producao_eventos['Semanal'] == "1" } %> Semanal </td>
        <td><%= n.check_box 'Mensal', { :checked => @questionario_basico_entidade.frequencia_producao_eventos['Mensal'] == "1" } %> Mensal </td>
        <td><%= n.check_box 'Anual', { :checked => @questionario_basico_entidade.frequencia_producao_eventos['Anual'] == "1" } %> Anual </td>
        <td><%= n.check_box 'Outros', { :checked => @questionario_basico_entidade.frequencia_producao_eventos['Outros'] == "1" } %> Outros </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>
<div class="control-group">
  <%= f.label :participa_eventos, 'Participa de Eventos?', :class => 'control-label' %>
  <div class="controls">
    <%= f.select :participa_eventos, 'Sim' => true, 'Não' => false %>
  </div>
</div>

<div class="control-group">
  <%= f.label :frequencia_participacao_eventos, 'Participa com que Frequência', :class => 'control-label' %>
  <div class="controls">
    <%= f.fields_for :frequencia_participacao_eventos, @questionario_basico_entidade.frequencia_participacao_eventos do |n| %>
    <table>
      <tr>
        <td><%= n.check_box 'Diário', { :checked => @questionario_basico_entidade.frequencia_participacao_eventos['Diário'] == "1" } %> Diário </td>
        <td><%= n.check_box 'Semanal', { :checked => @questionario_basico_entidade.frequencia_participacao_eventos['Semanal'] == "1" } %> Semanal </td>
        <td><%= n.check_box 'Mensal', { :checked => @questionario_basico_entidade.frequencia_participacao_eventos['Mensal'] == "1" } %> Mensal </td>
        <td><%= n.check_box 'Anual', { :checked => @questionario_basico_entidade.frequencia_participacao_eventos['Anual'] == "1" } %> Anual </td>
        <td><%= n.check_box 'Outros', { :checked => @questionario_basico_entidade.frequencia_participacao_eventos['Outros'] == "1" } %> Outros </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

<%= f.hidden_field :entidade_equipamento_id, :value => @entidade_equipamento.id %>

<% if params[:action] == 'new' %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

<div class="form-actions">
  <%= f.submit 'Responder Questionário', :class => 'btn btn-primary', :disable_with => 'Enviando...' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidade_equipamento_questionario_basico_entidades_path, :class => 'btn' %>
</div>
<% end %>

app/views/questionario_basico_entidades/edit.html.erb
<div class="page-header">
  <h3>Editando Questionário Básico de <%= @entidade_equipamento.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@entidade_equipamento) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Saiba Mais", entidade_equipamento_questionario_basico_entidades_path(@entidade_equipamento) %>
    </li>
    <li class="active">
      <%= link_to "Editando Questionário " + @entidade_equipamento.nome, edit_entidade_equipamento_questionario_basico_entidade_path(@entidade_equipamento, @questionario_basico_entidade) %>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>

app/views/questionario_basico_entidades/index.html.erb
<div class="page-header">
  <h3><%= @entidade_equipamento.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@entidade_equipamento) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@entidade_equipamento) %>
    </li>
    <li class="active">
      <%= link_to "Saiba Mais", entidade_equipamento_questionario_basico_entidades_path(@entidade_equipamento) %>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <% if @questionario_basico_entidades.empty? %>
        <br/>
        <h3 style="text-align: center;">
          Nenhuma Informação Registrada.
          <br/>
          <% if user_signed_in? %>
            <% if  (current_user.id == @entidade_equipamento.user_id) || (current_user.admin?) %>
              <%= link_to "Responder Questionário?", new_entidade_equipamento_questionario_basico_entidade_path if user_signed_in?%>
            <% end %>
          <% end %>
        </h3>
        <br/>
        </br>
      <% else %>

      <% @questionario_basico_entidades.each do |questionario_basico_entidade_equipamento| %>

      <% if user_signed_in? %>
        <% if (current_user.id == questionario_basico_entidade_equipamento.user_id || current_user.admin?) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_equipamento_questionario_basico_entidade_path(@entidade_equipamento, questionario_basico_entidade_equipamento), :class => 'btn' %>
        <% end %>
      <% end %>

      <dl class="dl-horizontal">
        <dt>
          <strong>Início das Atividades:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.inicio_atividades %>&nbsp;
        </dd>
        <dt>
          <strong>Resumo das Atividades:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.principais_atividades %>&nbsp;
        </dd>
        <dt>
          <strong>Ações Desenvolvidas:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.acoes_desenvolvidas.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>&nbsp;
        </dd>
        <dt>
          <strong>Frequência das Ações:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.frequencia_acoes.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>&nbsp;
        </dd>
        <dt>
          <strong>Produz Eventos?:</strong>
        </dt>
        <dd>
          <%= I18n.t(questionario_basico_entidade_equipamento.produz_eventos.to_s) %>&nbsp;
        </dd>
        <dt>
          <strong>Produz com que Frequência:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.frequencia_producao_eventos.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>&nbsp;
        </dd>
        <dt>
          <strong>Participa de Eventos?:</strong>
        </dt>
        <dd>
          <%= I18n.t(questionario_basico_entidade_equipamento.participa_eventos.to_s) %>&nbsp;
        </dd>
        <dt>
          <strong>Participa com que Frequência:</strong>
        </dt>
        <dd>
          <%= questionario_basico_entidade_equipamento.frequencia_participacao_eventos.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>&nbsp;
        </dd>
      </dl>
      <% end %>
      <% end %>
    </div>
  </div>

app/views/questionario_basico_entidades/new.html.erb
<div class="page-header">
  <h3><%= @entidade_equipamento.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@entidade_equipamento) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@entidade_equipamento) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@entidade_equipamento) %>
    </li>
    <li class="active">
      <%= link_to "Saiba Mais", entidade_equipamento_questionario_basico_entidades_path(@entidade_equipamento) %>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>

app/views/questionario_basico_entidades/show.html.erb
<% - model_class = QuestionarioBasicoEntidade -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt>
    <strong>Início das Atividades:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.inicio_atividades %>
  </dd>
  <dt>
    <strong>Resumo das Atividades:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.principais_atividades %>
  </dd>
  <dt>
    <strong>Ações Desenvolvidas:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.acoes_desenvolvidas.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>
  </dd>
  <dt>
    <strong>Frequência das Ações:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.frequencia_acoes.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>
  </dd>
  <dt>
    <strong>Produz Eventos?:</strong>
  </dt>
  <dd>
    <%= I18n.t(@questionario_basico_entidade_equipamento.produz_eventos) %>
  </dd>
  <dt>
    <strong>Produz com que Frequência:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.frequencia_producao_eventos.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>
  </dd>
  <dt>
    <strong>Participa de Eventos?:</strong>
  </dt>
  <dd>
    <%= I18n.t(@questionario_basico_entidade_equipamento.participa_eventos) %>
  </dd>
  <dt>
    <strong>Participa com que Frequência:</strong>
  </dt>
  <dd>
    <%= @questionario_basico_entidade_equipamento.frequencia_participacao_eventos.map { |k, v| (v == '1' ? k : nil) }.join(' ') %>
  </dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), entidade_equipamento_questionario_basico_entidade_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_equipamento_questionario_basico_entidade_equipamento_path(@questionario_basico_entidade_equipamento), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
  entidade_equipamento_questionario_basico_entidade_equipamento_path(@questionario_basico_entidade_equipamento),
  :method => 'delete',
  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) },
  :class => 'btn btn-danger' %>
</div>