config/routes.rb
Mapadacultura::Application.routes.draw do
  devise_for :users
    as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  resources :entidade_equipamentos, :path => :registros do
    resources :questionario_basico_entidades, :path => 'questionario'
    resources :fotos,  :controller => "fotos"
    resources :videos, :controller => "videos" do
      get 'view', :action => 'view', :as => 'view'
    end

    collection do
      get 'entidades/',           :action => 'entidades'
      get 'equipamentos/',        :action => 'equipamentos'
      get 'view/entidade/:id',    :action => 'entidade'
      get 'view/equipamento/:id', :action => 'equipamento'
      get 'view/atividade/:id',   :action => 'atividade', :as => 'atividade'
      get 'view/subcategoria/:id',:action => 'subcategoria', :as => 'subcategoria'
      get 'apresenta/:id',        :action => 'apresenta', :as => 'apresenta'
      get 'publish/:id',          :action => 'publish',   :as => 'publish'
      get 'evaluate'
      get 'search'
    end
  end

  resources :tipos
  resources :tipo_equipamentos
  resources :tipo_naturezas
  resources :atividades, :path => :categorias
  resources :subcategorias
  resources :users

  get '/estados/:sigla/cidades', :as => :cidades, :to => 'cidades#index'
  get '/cep/:cep', :to => 'application#cep'

  get "home/index"
  get "home/sobre"

  root :to => 'home#index'
end

app/models/video.rb
# encoding: utf-8

class Video < ActiveRecord::Base
  attr_accessible :descricao, :nome, :publicar, :slug, :video, :entidade_equipamento_id, :user_id

  belongs_to :user
  belongs_to :entidade_equipamento

  has_attached_file :video,
                    :url => "/system/entidade_equipamentos/videos/:id/:filename",
                    :path => ":rails_root/public/system/entidade_equipamentos/videos/:id/:filename",
                    :styles => { :medium => { :geometry => "640x480", :format => 'ogv', 
                                              :convert_options => { :output => { :acodec => 'libvorbis', :ab => '128k', :ac => 2 } } 
                                            },
                                 :thumb  => { :geometry => "300x300#", :format => 'jpg', :time => 10 }
                               }, :processors => [:ffmpeg]

  extend FriendlyId
  friendly_id :nome, use: :slugged
end

app/controllers/videos_controller.rb
# encoding: utf-8

class VideosController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  layout nil, :only => :view

  def create
    @video = Video.new(params[:video])
    @dados = EntidadeEquipamento.find(@video.entidade_equipamento_id)

    respond_to do |format|
      if @video.save
        format.html { redirect_to entidade_equipamento_videos_path, notice: 'O Vídeo foi adicionada com Sucesso.' }
        format.json { render json: entidade_equipamento_videos_path, status: :created, location: @dados }
      else
        format.html { render action: "new" }
        format.json { render json: @dados.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @video = Video.new
    @dados = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  def edit
    @video = Video.find(params[:id])
    @dados = EntidadeEquipamento.find(@video.entidade_equipamento_id)

    return false if !owner_verify(@dados, entidade_equipamentos_url)
  end

  def update
    @video = Video.find(params[:id])
    @dados = EntidadeEquipamento.find(@video.entidade_equipamento_id)

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to entidade_equipamento_videos_path, notice: 'O Vídeo foi atualizado com Sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dados.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @dados = EntidadeEquipamento.find(params[:entidade_equipamento_id])
    @videos = Video.where("entidade_equipamento_id = #{@dados.id}")

    respond_to do |format|
      format.html
      format.json { render json: @dados }
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @dados = EntidadeEquipamento.find(@video.entidade_equipamento_id)

    return false if !owner_verify(@dados, entidade_equipamento_url)

    @video.destroy

    respond_to do |format|
      format.html { redirect_to entidade_equipamento_videos_path }
      format.json { head :no_content }
    end
  end

  # GET /videos/view/1
  def view
    @video = Video.find(params[:video_id])
    render :layout => false
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for [@dados, @video], :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
  <%= f.label :nome, 'Nome', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :nome, :autofocus => true, :class => 'span4', :size => '64', :maxlength => '254' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :descricao, 'Descrição', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :descricao, :class => 'span6', :size => '64', :maxlength => '254' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :video, 'Video', :class => 'control-label' %>
  <div class="controls">
    <%= f.file_field :video %>
  </div>
</div>

<%= f.hidden_field :entidade_equipamento_id, :value => @dados.id %>

<% if params[:action] == 'new' %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary', :disable_with => 'Enviando...' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidade_equipamento_videos_path, :class => 'btn' %>
</div>
<% end %>

app/views/videos/edit.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>    
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Editando " + @video.nome %></a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>

app/views/videos/index.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <% if @dados.tipo_id != 2 %>
      <li>
        <%= link_to "Saiba Mais", entidade_equipamento_questionario_basico_entidades_path(@dados) %>
      </li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">

      <% if user_signed_in? %>
      <% if (current_user.id == @dados.user_id || current_user.admin?) %>
      <%= link_to t('.new', :default => t("helpers.links.new")), new_entidade_equipamento_video_path, :class => 'btn btn-primary' if ! @videos.empty?%>
      <% end %>
      <% end %>

      <% if @videos.empty? %>
        <br/>
        <h3 style="text-align: center;">
          Nenhum Vídeo Encontrado.
          <br/>
          <% if user_signed_in? %>
            <% if  (current_user.id == @dados.user_id) || (current_user.admin?) %>
              <%= link_to "Adicionar novo Vídeo?", new_entidade_equipamento_video_path if user_signed_in?%>
            <% end %>
          <% end %>
        </h3>
        <br/>
        </br>
      <% else %>
        <div id="gallery">
          <ul id="grid">
            <% @videos.each do |video| %>
             <li>
              <%= link_to (image_tag video.video.url(:thumb), :alt => video.nome, :title => video.nome, :width => '150'), entidade_equipamento_video_view_path(@dados, video), :id => 'video-box', :class => 'popover-image', 'data-content' => video.nome, 'data-placement' => 'top' %></td>
              <%= link_to t('Baixar Original', :default => 'Baixar Original'), video.video.url(:original), :class => 'btn btn-mini btn-success' %>

              <% if user_signed_in? %>
                <% if (current_user.id == @dados.user_id || current_user.admin?) %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_equipamento_video_path(@dados, video), :class => 'btn btn-mini' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_equipamento_video_path(@dados, video), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você esta certo?')) }, :class => 'btn btn-mini btn-danger' %>
                <% end %>
              <% end %>
             </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

app/views/videos/new.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Adicionar Vídeo"%></a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @video.nome %>
</p>

<p>
  <b>Slug:</b>
  <%= @video.slug %>
</p>

<p>
  <b>Descricao:</b>
  <%= @video.descricao %>
</p>

<p>
  <b>Publicar:</b>
  <%= @video.publicar %>
</p>

<p>
  <b>User:</b>
  <%= @video.user %>
</p>

<p>
  <b>Entidade equipamento:</b>
  <%= @video.entidade_equipamento %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/view.html.erb
<!DOCTYPE html>

<!-- 
    Mapa da Cultura - GPLv3
    Copyright (C) 2013 Marcelo Soares Souza <marcelo@juntadados.org>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<html lang="pt-br">
  <body>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <div style="text-align: center;">
      <video id="<%= @video.nome %>" class="video-js vjs-default-skin" controls preload="auto" width="360" height="240" poster="<%= @video.video.url(:thumb) %>" data-setup="{}">
        <source src="<%= @video.video.url(:medium) %>" type="video/ogg">
      </video>
    </div>

  </body>
</html>