config/routes.rb
Mapadacultura::Application.routes.draw do
  devise_for :users
    as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  resources :entidade_equipamentos, :path => :registros do
    resources :questionario_basico_entidades, :path => 'questionario'
    resources :fotos,  :controller => "fotos"
    resources :videos, :controller => "videos" do
      get 'view', :action => 'view', :as => 'view'
    end

    collection do
      get 'entidades/',           :action => 'entidades'
      get 'equipamentos/',        :action => 'equipamentos'
      get 'view/entidade/:id',    :action => 'entidade'
      get 'view/equipamento/:id', :action => 'equipamento'
      get 'view/atividade/:id',   :action => 'atividade', :as => 'atividade'
      get 'view/subcategoria/:id',:action => 'subcategoria', :as => 'subcategoria'
      get 'apresenta/:id',        :action => 'apresenta', :as => 'apresenta'
      get 'publish/:id',          :action => 'publish',   :as => 'publish'
      get 'evaluate'
      get 'search'
    end
  end

  resources :tipos
  resources :tipo_equipamentos
  resources :tipo_naturezas
  resources :atividades, :path => :categorias
  resources :subcategorias
  resources :users

  get '/estados/:sigla/cidades', :as => :cidades, :to => 'cidades#index'
  get '/cep/:cep', :to => 'application#cep'

  get "home/index"
  get "home/sobre"

  root :to => 'home#index'
end

app/models/foto.rb
# encoding: utf-8

class Foto < ActiveRecord::Base
  attr_accessible :descricao, :nome, :publicar, :slug, :foto, :entidade_equipamento_id, :user_id

  belongs_to :user
  belongs_to :entidade_equipamento

  has_attached_file :foto,
                    :url  => "/system/entidade_equipamentos/fotos/:id/:basename_:style.:extension",
                    :path => ":rails_root/public/system/entidade_equipamentos/fotos/:id/:basename_:style.:extension",
                    :styles => { :medium => "300x300>", :thumb => "150x150>" }

  extend FriendlyId
  friendly_id :nome, use: :slugged
end

app/controllers/fotos_controller.rb
# encoding: utf-8

class FotosController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  def create
    @foto = Foto.new(params[:foto])
    @dados = EntidadeEquipamento.find(@foto.entidade_equipamento_id)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to entidade_equipamento_fotos_path, notice: 'A Foto foi adicionada com Sucesso.' }
        format.json { render json: entidade_equipamento_fotos_path, status: :created, location: @dados }
      else
        format.html { render action: "new" }
        format.json { render json: @dados.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @foto = Foto.new
    @dados = EntidadeEquipamento.find(params[:entidade_equipamento_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  def edit
    @foto = Foto.find(params[:id])
    @dados = EntidadeEquipamento.find(@foto.entidade_equipamento_id)

    return false if !owner_verify(@dados, entidade_equipamentos_url)
  end

  def update
    @foto = Foto.find(params[:id])
    @dados = EntidadeEquipamento.find(@foto.entidade_equipamento_id)

    respond_to do |format|
      if @foto.update_attributes(params[:foto])
        format.html { redirect_to entidade_equipamento_fotos_path, notice: 'A Foto foi atualizada com Sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dados.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @dados = EntidadeEquipamento.find(params[:entidade_equipamento_id])
    @fotos = Foto.where("entidade_equipamento_id = #{@dados.id}")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dados }
    end
  end

  def destroy
    @foto = Foto.find(params[:id])
    @dados = EntidadeEquipamento.find(@foto.entidade_equipamento_id)

    return false if !owner_verify(@dados, entidade_equipamento_url)

    @foto.destroy

    respond_to do |format|
      format.html { redirect_to entidade_equipamento_fotos_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for [@dados, @foto], :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
  <%= f.label :nome, 'Nome', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :nome, :autofocus => true, :class => 'span4', :size => '64', :maxlength => '254' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :descricao, 'Descrição', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :descricao, :class => 'span6', :size => '64', :maxlength => '254' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :foto, 'Foto', :class => 'control-label' %>
  <div class="controls">
    <%= f.file_field :foto %>
  </div>
</div>

<%= f.hidden_field :entidade_equipamento_id, :value => @dados.id %>

<% if params[:action] == 'new' %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary', :disable_with => 'Enviando...' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidade_equipamento_fotos_path, :class => 'btn' %>
</div>
<% end %>

app/views/fotos/edit.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>    
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Editando " + @foto.nome %></a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>

app/views/fotos/index.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <% if @dados.tipo_id != 2 %>
      <li>
        <%= link_to "Saiba Mais", entidade_equipamento_questionario_basico_entidades_path(@dados) %>
      </li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">

      <% if user_signed_in? %>
      <% if (current_user.id == @dados.user_id || current_user.admin?) %>
      <%= link_to t('.new', :default => t("helpers.links.new")), new_entidade_equipamento_foto_path, :class => 'btn btn-primary' if ! @fotos.empty?%>
      <% end %>
      <% end %>

      <% if @fotos.empty? %>
        <br/>
        <h3 style="text-align: center;"> 
          Nenhuma Foto Encontrada.
          <br/>
          <% if user_signed_in? %>
            <% if  (current_user.id == @dados.user_id) || (current_user.admin?) %>
              <%= link_to "Adicionar nova Foto?", new_entidade_equipamento_foto_path if user_signed_in?%> 
            <% end %>
          <% end %>
        </h3>
        <br/>
        </br>
      <% else %>
        <div id="gallery">
          <ul id="grid">
            <% @fotos.each do |foto| %>
             <li>
              <%= link_to (image_tag foto.foto.url(:thumb), :alt => foto.nome, :title => foto.nome), foto.foto.url,  :id => 'image-box', :class => 'popover-image', 'data-content' => foto.nome, 'data-placement' => 'top' %>
              <% if user_signed_in? %>
                <% if (current_user.id == @dados.user_id || current_user.admin?) %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_equipamento_foto_path(@dados, foto), :class => 'btn btn-mini' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_equipamento_foto_path(@dados, foto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você esta certo?')) }, :class => 'btn btn-mini btn-danger' %>
                <% end %>
              <% end %>
             </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

app/views/fotos/new.html.erb
<div class="page-header">
  <h3><%= @dados.nome %></h3>

  <ul class="nav nav-tabs">
    <li>
      <a href="<%= entidade_equipamento_path(@dados) %>">Dados Gerais</a>
    </li>
    <li>
      <%= link_to "Apresentação (Vídeo)", apresenta_entidade_equipamentos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Fotos", entidade_equipamento_fotos_path(@dados) %>
    </li>
    <li>
      <%= link_to "Vídeos", entidade_equipamento_videos_path(@dados) %>
    </li>
    <li class="active">
      <%= link_to "Adicionar Foto"%></a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="active tab-pane" id="list">
      <%= render :partial => 'form' %>
    </div>
  </div>